# -*- coding: utf-8 -*-
"""functional-model-age-gender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKfLPermuS6nTMvdFVXUBivHEblFMQR-
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d jangedoo/utkface-new

import zipfile
zip = zipfile.ZipFile("/content/utkface-new.zip",'r')
zip.extractall("/content")
zip.close()

import os
import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.image import ImageDataGenerator

folder_path = '/content/utkface_aligned_cropped/UTKFace'

age=[]
gender=[]
img_path=[]
for file in os.listdir(folder_path):
  age.append(int(file.split('_')[0]))
  gender.append(int(file.split('_')[1]))
  img_path.append(file)

len(age)

df = pd.DataFrame({'age':age,'gender':gender,'img':img_path})

df.shape

df.head()

train_df = df.sample(frac=1,random_state=0).iloc[:20000]
test_df = df.sample(frac=1,random_state=0).iloc[20000:]

train_df.shape

test_df.shape

train_datagen = ImageDataGenerator(rescale=1./255,
                                   rotation_range=30,
                                   width_shift_range=0.2,
                                   height_shift_range=0.2,
                                   shear_range=0.2,
                                   zoom_range=0.2,
                                   horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    directory=folder_path,
    x_col='img',
    y_col=['age', 'gender'],
    target_size=(200, 200),
    batch_size=32,
    class_mode='multi_output',
    shuffle=True
)

test_generator = test_datagen.flow_from_dataframe(
    dataframe=test_df,
    directory=folder_path,
    x_col='img',
    y_col=['age', 'gender'],
    target_size=(200, 200),
    batch_size=32,
    class_mode='multi_output',
    shuffle=False
)

train_df['age'] = train_df['age'].astype(float)
test_df['age']  = test_df['age'].astype(float)

train_df['gender'] = train_df['gender'].astype(int)
test_df['gender']  = test_df['gender'].astype(int)

from keras.applications.vgg16 import VGG16
from keras.layers import *
from keras.models import Model



vggnet = VGG16(include_top=False, input_shape=(200,200,3))

vggnet.trainable=False

output = vggnet.layers[-1].output

flatten = Flatten()(output)

dense1 = Dense(512, activation='relu')(flatten)
dense2 = Dense(512,activation='relu')(flatten)

dense3 = Dense(512,activation='relu')(dense1)
dense4 = Dense(512,activation='relu')(dense2)

output1 = Dense(1,activation='linear',name='age')(dense3)
output2 = Dense(1,activation='sigmoid',name='gender')(dense4)

model = Model(inputs=vggnet.input,outputs=[output1,output2])

model.summary()

from keras.utils import plot_model
plot_model(model)

model.compile(optimizer='adam', loss={'age': 'mae', 'gender': 'binary_crossentropy'}, metrics={'age': 'mae', 'gender': 'accuracy'},loss_weights={'age':1,'gender':99})

def wrap_generator(generator):
    for x, y in generator:
        # y is a list of [age_labels, gender_labels]
        # We need to convert it to a dictionary matching the model's output names
        yield x, {'age': y[0], 'gender': y[1]}

model.fit(
    wrap_generator(train_generator),
    validation_data=wrap_generator(test_generator),
    epochs=10
)



