# -*- coding: utf-8 -*-
"""functional-model-in-keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8k_VYGN4Whqon6yVK6TEhabgx1LL525
"""

from keras.models import Model

model=Model(inputs=x, outputs=[output1,output2])

from keras.layers import *

x=Input(shape=(3,))

hidden1=Dense(128,activation='relu')(x)
hidden2=Dense(64,activation='relu')(hidden1)

output1=Dense(1,activation='linear')(hidden2)
output2=Dense(1,activation='sigmoid')(hidden2)

model.summary()

from keras.utils import plot_model
plot_model(model,show_shapes=True)

